# Generated by Django 4.2.4 on 2023-09-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('objetivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veteranos', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('PO', models.CharField(help_text='Nome e Sobrenome', max_length=50, verbose_name='Product Owner: ')),
                ('backEnd1', models.CharField(help_text='Nome e Sobrenome', max_length=50, verbose_name='1° Backend: ')),
                ('backEnd2', models.CharField(blank=True, help_text='Nome e Sobrenome', max_length=50, verbose_name='2° Backend(opcional): ')),
                ('backEnd3', models.CharField(blank=True, help_text='Nome e Sobrenome', max_length=50, verbose_name='3° Backend(opcional): ')),
                ('frontEnd', models.CharField(help_text='Nome e Sobrenome', max_length=50, verbose_name='Front End: ')),
                ('projeto', models.ForeignKey(help_text='Selecione qual projeto você deseja relacionar com esse grupo', max_length=120, on_delete=django.db.models.deletion.CASCADE, to='fabrica.projeto')),
            ],
        ),
    ]
